export const ACCOUNT_LIST_REQUEST = "ACCOUNT_LIST_REQUEST"
export const ACCOUNT_LIST_SUCCESS = "ACCOUNT_LIST_SUCCESS"
export const ACCOUNT_LIST_FAIL = "ACCOUNT_LIST_FAIL"
export const ACCOUNT_LIST_RESET = "ACCOUNT_LIST_RESET"

export const ACCOUNT_REGISTER_REQUEST = "ACCOUNT_REGISTER_REQUEST"
export const ACCOUNT_REGISTER_SUCCESS = "ACCOUNT_REGISTER_SUCCESS"
export const ACCOUNT_REGISTER_FAIL = "ACCOUNT_REGISTER_FAIL"
export const ACCOUNT_REGISTER_RESET = "ACCOUNT_REGISTER_RESET"

export const ACCOUNT_DELETE_REQUEST = "ACCOUNT_DELETE_REQUEST"
export const ACCOUNT_DELETE_SUCCESS = "ACCOUNT_DELETE_SUCCESS"
export const ACCOUNT_DELETE_FAIL = "ACCOUNT_DELETE_FAIL"
export const ACCOUNT_DELETE_RESET = "ACCOUNT_DELETE_RESET"

export const ACCOUNT_UPDATE_REQUEST = "ACCOUNT_UPDATE_REQUEST"
export const ACCOUNT_UPDATE_SUCCESS = "ACCOUNT_UPDATE_SUCCESS"
export const ACCOUNT_UPDATE_FAIL = "ACCOUNT_UPDATE_FAIL"
export const ACCOUNT_UPDATE_RESET = "ACCOUNT_UPDATE_RESET"

export const ACCOUNT_DETAIL_REQUEST = "ACCOUNT_DETAIL_REQUEST"
export const ACCOUNT_DETAIL_SUCCESS = "ACCOUNT_DETAIL_SUCCESS"
export const ACCOUNT_DETAIL_FAIL = "ACCOUNT_DETAIL_FAIL"
export const ACCOUNT_DETAIL_RESET = "ACCOUNT_DETAIL_RESET" 