export const ACTOR_LIST_REQUEST = "ACTOR_LIST_REQUEST"
export const ACTOR_LIST_SUCCESS = "ACTOR_LIST_SUCCESS"
export const ACTOR_LIST_FAIL = "ACTOR_LIST_FAIL"
export const ACTOR_LIST_RESET = "ACTOR_LIST_RESET"

export const ACTOR_REGISTER_REQUEST = "ACTOR_REGISTER_REQUEST"
export const ACTOR_REGISTER_SUCCESS = "ACTOR_REGISTER_SUCCESS"
export const ACTOR_REGISTER_FAIL = "ACTOR_REGISTER_FAIL"
export const ACTOR_REGISTER_RESET = "ACTOR_REGISTER_RESET"

export const ACTOR_UPDATE_REQUEST = "ACTOR_UPDATE_REQUEST"
export const ACTOR_UPDATE_SUCCESS = "ACTOR_UPDATE_SUCCESS"
export const ACTOR_UPDATE_FAIL = "ACTOR_UPDATE_FAIL"
export const ACTOR_UPDATE_RESET = "ACTOR_UPDATE_RESET"

export const ACTOR_DETAIL_REQUEST = "ACTOR_DETAIL_REQUEST"
export const ACTOR_DETAIL_SUCCESS = "ACTOR_DETAIL_SUCCESS"
export const ACTOR_DETAIL_FAIL = "ACTOR_DETAIL_FAIL"
export const ACTOR_DETAIL_RESET = "ACTOR_DETAIL_RESET"

export const ACTOR_DELETE_REQUEST = "ACTOR_DELETE_REQUEST"
export const ACTOR_DELETE_SUCCESS = "ACTOR_DELETE_SUCCESS"
export const ACTOR_DELETE_FAIL = "ACTOR_DELETE_FAIL"
export const ACTOR_DELETE_RESET = "ACTOR_DELETE_RESET"