export const EPISODE_LIST_REQUEST = "EPISODE_LIST_REQUEST"
export const EPISODE_LIST_SUCCESS = "EPISODE_LIST_SUCCESS"
export const EPISODE_LIST_FAIL = "EPISODE_LIST_FAIL"
export const EPISODE_LIST_RESET = "EPISODE_LIST_RESET"

export const EPISODE_REGISTER_REQUEST = "EPISODE_REGISTER_REQUEST"
export const EPISODE_REGISTER_SUCCESS = "EPISODE_REGISTER_SUCCESS"
export const EPISODE_REGISTER_FAIL = "EPISODE_REGISTER_FAIL"
export const EPISODE_REGISER_RESET = "EPISODE_REGISER_RESET"

export const EPISODE_UPDATE_REQUEST = "EPISODE_UPDATE_REQUEST"
export const EPISODE_UPDATE_SUCCESS = "EPISODE_UPDATE_SUCCESS"
export const EPISODE_UPDATE_FAIL = "EPISODE_UPDATE_FAIL"
export const EPISODE_UPDATE_RESET = "EPISODE_UPDATE_RESET"

export const EPISODE_DETAIL_REQUEST = "EPISODE_DETAIL_REQUEST"
export const EPISODE_DETAIL_SUCCESS = "EPISODE_DETAIL_SUCCESS"
export const EPISODE_DETAIL_FAIL = "EPISODE_DETAIL_FAIL"
export const EPISODE_DETAIL_RESET = "EPISODE_DETAIL_RESET"

export const EPISODE_DELETE_REQUEST = "EPISODE_DELETE_REQUEST"
export const EPISODE_DELETE_SUCCESS = "EPISODE_DELETE_SUCCESS"
export const EPISODE_DELETE_FAIL = "EPISODE_DELETE_FAIL"
export const EPISODE_DELETE_RESET = "EPISODE_DELETE_RESET"