
export const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST";

export const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS";

export const MOVIE_LIST_FAIL = "MOVIE_LIST_FAIL";

export const MOVIE_LIST_RESET = "MOVIE_LIST_RESET";

export const MOVIE_REGISTER_REQUEST = "MOVIE_REGISTER_REQUEST";
export const MOVIE_REGISTER_SUCCESS = "MOVIE_REGISTER_SUCCESS";
export const MOVIE_REGISTER_FAIL = "MOVIE_REGISTER_FAIL";
export const MOVIE_REGISTER_RESET = "MOVIE_REGISTER_RESET";

export const MOVIE_DELETE_REQUEST = "MOVIE_DELETE_REQUEST";

export const MOVIE_DELETE_SUCCESS = "MOVIE_DELETE_SUCCESS";
export const MOVIE_DELETE_FAIL = "MOVIE_DELETE_FAIL";

export const MOVIE_DELETE_RESET = "MOVIE_DELETE_RESET";

export const MOVIE_UPDATE_REQUEST = "MOVIE_UPDATE_REQUEST"
export const MOVIE_UPDATE_SUCCESS = "MOVIE_UPDATE_SUCCESS"
export const MOVIE_UPDATE_FAIL = "MOVIE_UPDATE_FAIL"
export const MOVIE_UPDATE_RESET = "MOVIE_UPDATE_RESET"

export const MOVIE_DETAIL_REQUEST = "MOVIE_DETAIL_REQUEST"
export const MOVIE_DETAIL_SUCCESS = "MOVIE_DETAIL_SUCCESS"
export const MOVIE_DETAIL_FAIL = "MOVIE_DETAIL_FAIL"
export const MOVIE_DETAIL_RESET = "MOVIE_DETAIL_RESET"