export const UPLOAD_FILE_REQUEST = "UPLOAD_FILE_REQUEST"
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS"
export const UPLOAD_FILE_FAIL = "UPLOAD_FILE_FAIL"
export const UPLOAD_FILE_RESET = "UPLOAD_FILE_RESET"


export const UPLOAD_VIDEO_REQUEST = "UPLOAD_VIDEO_REQUEST"
export const UPLOAD_VIDEO_SUCCESS = "UPLOAD_VIDEO_SUCCESS"
export const UPLOAD_VIDEO_FAIL = "UPLOAD_VIDEO_FAIL"
export const UPLOAD_VIDEO_RESET = "UPLOAD_VIDEO_RESET"

